config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
  # dingtalk router
  get 'issues/:id/dingtalk_flow', :to => 'dingtalk#start_dingtalk_flow', :as => 'start_dingtalk_flow'

app/models/corp_wechat.rb
class CorpWechat < ActiveRecord::Base
  unloadable
  validates_presence_of :corp_id,:corp_secret,:app_name,:corp_name
  validates :app_id, presence: true, uniqueness: true
end

app/controllers/corp_wechats_controller.rb
class CorpWechatsController < ApplicationController
    unloadable
  #skip_before_filter :verify_authenticity_token
  #before_filter :find_project, :authorize, :only => [:new,:index]
  layout 'admin'
  before_action :require_admin
  def new
    @corp_wechat = CorpWechat.new
  end
  
  def create
    @corp_wechat = CorpWechat.new(corp_wechat_params)
    if @corp_wechat.save
      flash[:notice] = l(:notice_successful_create)  
      redirect_to :action =>"plugin", :id => "redmine_qy_wechats", :controller => "settings", :tab => 'corp_wechat'
    else
      render :action => 'new'
    end
  end
  
  def edit
    @corp_wechat = CorpWechat.find(params[:id])
  end
  
  def update
    @corp_wechat = CorpWechat.find(params[:id])
    if @corp_wechat.update_attributes(corp_wechat_params)
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action =>"plugin", :id => "redmine_qy_wechats", :controller => "settings", :tab => 'corp_wechat'
    else
      render :action => 'edit'
    end
  end
  
  
  def destroy
    @corp_wechat = CorpWechat.find(params[:id])
    @corp_wechat.destroy
    respond_to do |format|
      format.html { redirect_to :controller => 'settings', :action => 'plugin', :id => 'redmine_qy_wechats', :tab => 'corp_wechat'}
      format.api { render_api_ok }
    end
    @corp_wechats = CorpWechat.all - [@corp_wechat]
  end
  
  private
    def corp_wechat_params
      params.require(:corp_wechat).permit(:corp_id, :corp_secret,:app_id,:corp_name,:app_name,:author_id,:project_id)
    end
    def find_project
      @project = Project.find(params[:project_id])
    end
end

app/controllers/dingtalk_controller.rb
class DingtalkController < ApplicationController
  def start_dingtalk_flow
    # flow_flag = Setting["plugin_redmine_work_wechat"]["dingtalk_approval_flow_enabled"]
    flow_flag = "0" 
    #填写确认并应用的企业ID
    corpid = Setting["plugin_redmine_work_wechat"]["dingtalk_corp_id"]
    #填写确认并应用的应用Secret
    corpsecret = Setting["plugin_redmine_work_wechat"]["dingtalk_corp_secret"]
    #填写正确的redmine审批部门
    approval_dept_id = Setting["plugin_redmine_work_wechat"]["dingtalk_approval_dept_id"]
      
    appid = Setting["plugin_redmine_work_wechat"]["dingtalk_app_id"]
    #对应的审批流编号
    approval_flow_no = Setting["plugin_redmine_work_wechat"]["dingtalk_approval_flow_no"]
    if flow_flag == "0" || corpid.blank? || corpsecret.blank? || appid.blank? || approval_dept_id.blank? || approval_flow_no.blank?
      flash[:notice] = l(:flash_dingtalk_setting_lack)
      @err_response = l(:lable_err_setting_null)
      return
    end
    
    # 获取issue参数
    @issue_id = params[:id]
    uri = URI.parse("https://oapi.dingtalk.com/gettoken?corpid=#{corpid}&corpsecret=#{corpsecret}")
    # 改成异常捕捉，避免is_valid?方法本身的出错
    begin
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(uri.request_uri)  
      response = http.request(request)
          
      # 获得token
      token = JSON.parse(response.body)["access_token"]
    
      url =  URI.parse("https://eco.taobao.com/router/rest")

      issue = Issue.find(@issue_id)
      # 获得任务信息
      issue_name = issue.subject
      issue_desc = issue.description
      project_name = issue.project.name
      
      # 获得作者信息，并作为审批发起者
      author = issue.author
      author_dt_id = author.dingtalk_account_number if !author.blank?
      if author_dt_id.blank?
        flash[:error] = l(:flash_dingtalk_flow_wrong)
        @err_response = l(:lable_err_author_null)
        return
      end
      
      
      # 获得指派者信息，作为审批者
      assign = issue.assigned_to
      assign_dt_id = assign.dingtalk_account_number if !assign.blank?
      if assign.blank? || assign_dt_id.blank?
        flash[:error] = l(:flash_dingtalk_flow_wrong)
        @err_response = l(:lable_err_assign_null)
        return
      end
      # 获得跟踪者信息，作为抄送者
      watchers = issue.watchers
      watchers_dt_ids = ""
      watchers.each do |w|
        unless w.blank? && w.user.blank? && w.user.dingtalk_account_number.blank?
          watchers_dt_ids.concat(w.user.dingtalk_account_number).concat(",")
        end
      end
      
      params = {
        "format"=>"json",
        "method"=>"dingtalk.smartwork.bpms.processinstance.create",
        "partner_id"=>"apidoc",
        "session"=>token,
        "timestamp"=>"2017-09-14+16%3A34%3A52",
        "v"=>"2.0",
        "agent_id"=>appid,
        "approvers"=>assign_dt_id,
        "cc_position"=>"START",
        "dept_id"=>approval_dept_id,
        "form_component_values"=>"[{'name':'#{l(:flow_project_name)}','value':'#{project_name}'}, {'name':'#{l(:flow_issue_id)}','value':'#{@issue_id}'}, {'name':'#{l(:flow_issue_name)}','value':'#{issue_name}'}, {'name':'#{l(:flow_issue_desc)}','value':'#{issue_desc}'}]",
        "originator_user_id"=>author_dt_id,
        "process_code"=>approval_flow_no,
        "cc_list"=>watchers_dt_ids
      }
      
      
      # "PROC-52IKRYIV-CVBONT54SMZ0MYIVMQLL1-XTRG4K7J-4"
      
      res = Typhoeus::Request.post("https://eco.taobao.com/router/rest", :params => params, :headers=>{"Content-type"=>"application/x-www-form-urlencoded", "charset"=>"utf-8"})
        
      # http = Net::HTTP.new(url.host,url.port)
      # http.use_ssl = true
      # #req = Net::HTTP::Post.new(url.path, initheader = {'Content-Type' =>'application/json'})
      # # req = Net::HTTP::Post.new(url.request_uri, 'Content-Type' => 'application/json')
      # req = Net::HTTP::Post.new(url.request_uri, 'Content-Type' => 'application/x-www-form-urlencoded;charset=utf-8')
          

      
      # req.body = data
      # res = http.request(req)
      res_body = JSON.parse(res.body)
      error_response = res_body["error_response"]
      
      if error_response.blank?
        flash[:notice] = l(:flash_dingtalk_flow_start)
      else
        flash[:error] = l(:flash_dingtalk_flow_wrong)
        @err_response = error_response
      end
    rescue
      flash[:error] = l(:flash_dingtalk_flow_wrong)
      @err_response = l(:lable_err_unknown)
    end
    
    
  end
  
  # private
end

app/helpers/corp_wechats_helper.rb
module CorpWechatsHelper
    def a
    end
end

app/views/corp_wechats/_form.html.erb
<div class="box tabular attributes">
    <div class="splitcontentleft">
        <p><%= f.text_field :corp_name, :label => :label_corp_name, :required => true  %></p>
        <p><%= f.text_field :corp_id, :label => :label_corpid, :required => true  %></p>
        <p><%= f.text_field :app_id, :label => :label_application_agentid, :required => true  %></p>
    </div>
    <div class="splitcontentright">
        <p><%= f.text_field :app_name, :label => :label_app_name, :required => true  %></p>
        <p><%= f.text_field :corp_secret, :label => :label_application_secret, :required => true  %></p>
    </div>
    <div style="clear:both"> 
        
    </div>
</div>

app/views/corp_wechats/edit.html.erb
<h2><%= l(:label_edit_qy_wechat) %></h2>
<%= labelled_form_for @corp_wechat, :url => {:action => 'update', :id => @corp_wechat.id}, :html => { :multipart => true, :method => :put, :id => 'corp_wechat_form'} do |f|  %>
  <%= render :partial => 'form', :locals => {:f => f}  %> 
  <%= submit_tag l(:button_save) -%>
<% end -%>

app/views/corp_wechats/new.html.erb
<h2><%= l(:label_new_qy_wecaht) %></h2>
<%= labelled_form_for :corp_wechat, @corp_wechat, :url => {:action => 'create', :project_id => @project}, :html => { :multipart => true, :id => 'corp_wechat_form'} do |f|  %>
  <%= render :partial => 'form', :locals => {:f => f}  %> 
  <%= submit_tag l(:button_save) %>
<% end -%>

app/views/dingtalk/start_dingtalk_flow.html.erb
<p>
  <% if !@err_response.blank? %>
    <%= @err_response %>
  <% else %>
    <%= l(:label_success_tip) %>
  <% end %>
</p>

app/views/issues/_dingtalk_flow.html.erb
<!--控制代码，判断是否需要加载-->
<% begin %>
<% flow_flag = '0' %>
<% corpid = Setting["plugin_redmine_work_wechat"]["dingtalk_corp_id"] %>
<% corpsecret = Setting["plugin_redmine_work_wechat"]["dingtalk_corp_secret"] %>
<% approval_dept_id = Setting["plugin_redmine_work_wechat"]["dingtalk_approval_dept_id"] %>
<% appid = Setting["plugin_redmine_work_wechat"]["dingtalk_app_id"] %>
<% approval_flow_no = Setting["plugin_redmine_work_wechat"]["dingtalk_approval_flow_no"] %>
<% rescue %>
  <% return %>
<% end %>
<% if flow_flag == '0' || corpid.blank? || corpsecret.blank? || appid.blank? || approval_dept_id.blank? || approval_flow_no.blank? %>
  <% return %>
<% end %>

<%= link_to l(:label_dingtalk_flow_start), start_dingtalk_flow_path %>

app/views/settings/_corp_wechat.html.erb
<% corp_wechat_tabs = [{:name => 'corp_wechat', :partial => 'settings/corp_wechat_setting', :label => :settings_wechat},
        {:name => 'dingtalk', :partial => 'settings/dingtalk_setting', :label => :settings_dingtalk},
        {:name => 'dingtalk_login', :partial => 'settings/dingtalk_login_setting', :label => :settings_dingtalk_login}]   %>   

<%= render_tabs corp_wechat_tabs %>

<% html_title(l(:label_settings), l(:labe_corp_wechats)) -%>  

app/views/settings/_corp_wechat_setting.html.erb
  <p>
    <label><%= l(:settings_corp_name) %></label>
    <%= text_field_tag 'settings[wechat_corp_name]', @settings["wechat_corp_name"], :size => 60 %>
  </p>
  <p>
    <label><%= l(:settings_corp_id) %></label>
    <%= text_field_tag 'settings[wechat_corp_id]', @settings["wechat_corp_id"], :size => 60 %>
  </p>
  <p>
    <label><%= l(:settings_app_name) %></label>
    <%= text_field_tag 'settings[wechat_app_name]', @settings["wechat_app_name"], :size => 60 %>
  </p>
  <p>
    <label><%= l(:settings_app_id) %></label>
    <%= text_field_tag 'settings[wechat_app_id]', @settings["wechat_app_id"], :size => 60 %>
  </p>
  <p>
    <label><%= l(:settings_app_secret) %></label>
    <%= text_field_tag 'settings[wechat_app_secret]', @settings["wechat_app_secret"], :size => 60 %>
  </p>

app/views/settings/_dingtalk_login_setting.html.erb
  <p>
    <label><%= l(:settings_dt_login_appid) %></label>
    <%= text_field_tag 'settings[dingtalk_login_appid]', @settings["dingtalk_login_appid"], :size => 60 %>
  </p>
  <p>
    <label><%= l(:settings_dt_login_appsecret) %></label>
    <%= text_field_tag 'settings[dingtalk_login_appsecret]', @settings["dingtalk_login_appsecret"], :size => 60 %>
  </p>
  <p>
    <label><%= l(:settings_dt_login_redirect) %></label>
    <%= text_field_tag 'settings[dingtalk_login_redirect]', @settings["dingtalk_login_redirect"], :size => 60 %>
  </p>

app/views/settings/_dingtalk_setting.html.erb
  <p>
    <label><%= l(:settings_dt_corp_id) %></label>
    <%= text_field_tag 'settings[dingtalk_corp_id]', @settings["dingtalk_corp_id"], :size => 60 %>
  </p>
  <p>
    <label><%= l(:settings_dt_app_id) %></label>
    <%= text_field_tag 'settings[dingtalk_app_id]', @settings["dingtalk_app_id"], :size => 60 %>
  </p>
  <p>
    <label><%= l(:settings_dt_corp_secret) %></label>
    <%= text_field_tag 'settings[dingtalk_corp_secret]', @settings["dingtalk_corp_secret"], :size => 60 %>
  </p>